### ISSUE TITLE
Rampant use of arithmetic '+' instead of bit-wise '|' 

### ISSUE THREAD

**Issue by danak6jq** [jwr/msp430_usi_i2c#1]
Don't use '+' to combine bits when you really mean to use '|'. Yes, the TI examples do that, it's wrong. Hint: what's '2 | 2'? OK, what's '2 + 2'. There's a reason they included bit-wise operators in C. Cheers.

**Comment by jwr** [comment]
Well, I see one line that uses '+', so perhaps it isn't *that* "rampant" 😃 

Anyway, I fully agree, and I don't know why that line made its way in. I think it's a leftover from TI examples. I'll fix it.

Thanks for pointing this out!

**Comment by jwr** [comment]
Actually, there were three lines that needed fixing. Fixed now. Thanks!

**Comment by danak6jq** [comment]
Indeed, this usage of '+' for bitwise OR shows up rampantly in the MSP430 example code. I've run into a case where MSP430 GRACE (the GUI tool) emits repeated instances of the same bit symbol, which result in silent bug:

#define  FOO     (1<<4)

baz = FOO + FOO;

Thanks!
